---
# SPDX-FileCopyrightText: 2022 Wilfred Nicoll <xyzroller@rollyourown.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Install Cron
  apt:
    name: cron
    update_cache: yes
    state: present
